### ISSUE TITLE
Add time drift and other NTPd metrics

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/sdc-cloud-analytics#2]
I don't know if this is the right place to ask but we recently had some CN lagging behind.
Since the ntp daemon is running in the global zone, there is no way for use to collect metrics from the zones.

I heard about the [RFD 27](https://github.com/joyent/rfd/blob/master/rfd/0027/README.md) and I don't know if it still worth implementing this in the cloud analytics or directly in the cmon-agent.

**Comment by jclulow** [comment]
What exact NTP metrics would you like to see?

At any rate, I think CMON is the right place for that kind of thing today.  @richardkiene and @davepacheco might like to chime in.

**Comment by benjamin-bergia** [comment]
Thanks for the quick reply.

I am far from being an expert on NTP so I guess in my case, delay, offset and jitter as in the [peer section of ntpq](https://www.eecis.udel.edu/~mills/ntp/html/ntpq.html) would be enough.

I am interested by the delay and offset between my CNs and HN not really between my HN and the ntp pool.

**Comment by benjamin-bergia** [comment]
We have deployed CMON on our environment so this task is not really relevant anymore. I will close it and open on on the CMON repository.
